config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'regions' => 'home#region', as: :region
  get 'shops' => 'shop#new', as: :shop
  post 'shop_create' => 'shop#create', as: :shop_create

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :children, class_name: "Country", foreign_key: "parent_id"
	belongs_to :parent, class_name: "Country"

	def self.search(query)
  		where("cname like ?", "%#{query}%") 
	end
end

app/models/location.rb
class Location < ActiveRecord::Base
	def self.search(query)
	  where("region_name like ?", "%#{query}%") 
	end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if params[:q]
			@duureg = Country.search(params[:q])
			@khoroolol = Location.search(params[:q])
		end
	end
	def region
		@duureg = Country.where(parent_id: nil)
	    if params[:d]
	      @d = Country.find(params[:d])
	      @khoroo = Country.where(parent_id: params[:d])
	      if params[:khoroo] =="true"
	        @khoroolol = Location.where(postcode: @d.cname)
	      end
	    else
	      @d = Country.where(parent_id: nil).first
	      @khoroo = []
	    end
	    if params[:kh] and params[:d] and params[:kh]!=""
	      @d = Country.find(params[:d])
	      @ckh = Country.find(params[:kh])
	    end
	end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
	def new
		@shop = Shop.new
		@shops = Shop.all
	end
	def create
		 @shop = Shop.new(params[:shop].permit(:name, :address, :email, :phone, :latlng))
		 	uploaded_io = params[:shop][:logo]
		 	filename = SecureRandom.hex + "-" + uploaded_io.original_filename
            File.open(Rails.root.join('public', 'uploads', filename), 'wb') do |file|
            	file.write(uploaded_io.read)
        	end
        	@shop.logo = filename
            if @shop.save
                    redirect_to shop_path
            else
                    render 'new'
            end
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/home/index.html.erb
<div class="container">
<div class="row">
  <form class="col s12">
    <div class="row">
      <div class="input-field offset-s2 col s7">
        <i class="mdi-action-search prefix"></i>
        <input id="icon_prefix" type="text" class="validate" name="q" value="<%= params[:q] %>">
        <label for="icon_prefix">Хайх</label>
      </div>
      <div class="input-field col s2">
		  <button class="btn waves-effect waves-light" type="submit">Хайх
		    <i class="mdi-content-send right"></i>
		  </button>
      </div>
    </div>
  </form>
</div>
<div class="row">
	<div id="map"></div>
</div>
<script>
$("#map").gmap3();
$(document).ready(function() {
	
	map = $("#map").gmap3("get");
	// new google.maps.KmlLayer({url: "http://91.228.52.236/kml/map_1.kml"}).setMap(map);
	// new google.maps.KmlLayer({url: "http://91.228.52.236/kml/map_2.kml"}).setMap(map);
	// new google.maps.KmlLayer({url: "http://91.228.52.236/kml/map_3.kml"}).setMap(map);
	// new google.maps.KmlLayer({url: "http://91.228.52.236/kml/map_4.kml"}).setMap(map);
	// new google.maps.KmlLayer({url: "http://91.228.52.236/kml/map_5.kml"}).setMap(map);
	// new google.maps.KmlLayer({url: "http://91.228.52.236/kml/map_6.kml"}).setMap(map);
	map.setCenter(new google.maps.LatLng(47.8916501, 106.9018714));
	map.setZoom(13);

	<% if @khoroolol %>
            <% @khoroolol.each do |k| %>
                  var coord = `<%=  k.coordinate %>`;
                  coords = [];
                  coord.split("\n").forEach(function(a,b){
                  c = a.split(",");
                  if(c.length > 1)
                     coords.push(new google.maps.LatLng(parseFloat(c[1]), parseFloat(c[0])));
                });
                var p = new google.maps.Polygon({
                paths: coords,
                strokeColor: '#FF0000',
                strokeOpacity:0.8,
                strokeWeight: 2,
                fillColor: '#FF0000',
                fillOpacity: 0.35,
                map: map
                });

              //p.setMap(map);
                  new google.maps.InfoWindow({position: new google.maps.LatLng(<%= k.center.split(",")[1] %>, <%= k.center.split(",")[0] %>), content: `<div style='height:40px; width: 100px;'><%= k.region_name.strip %></div>`}).setMap(map);
            <% end %>
          <% end %>


});
</script>
</div>
        

app/views/home/region.html.erb
<div class="col s12">
<div class="row">
	<div class="col s3">
      <ul class="collection">
      	<li class="collection-item">
      		<input type="checkbox" id="test5" onclick=" yousendit(this, 'khoroo')" <% if  params[:khoroo]=="true" %> checked <%  end %>/>
    		<label for="test5">Хороо, хотхон харуулах</label>
    	</li>
      <% @duureg.each do |location| %>
        <a href="?d=<%= location.id %>" class="collection-item <%= @d.id == location.id ? "active":"" %>"><%= location.cname%></a>
        	<% if @d.id == location.id %>
	        <ul class="collection">
	        	<% location.children.each do |kh| %>
	        		<a href="?d=<%= @d.id %>&kh=<%= kh.id %>" class="collection-item <%= params[:kh].to_i == kh.id ? "active":"" %>"><%= kh.cname %></a>
	        	<% end %>
	        </ul>
	       <% end %>
      <% end %>
      </ul>
	</div>
	<div class="col s9">
		<div id="map"></div>
	</div>

</div>
<script type="text/javascript">
	function yousendit(el,type){
    if($(el).is(':checked')){
        window.location="?d=<%= params[:d] %>&kh=<%= params[:kh] %>&"+type+"=true";
    }else window.location="?d=<%= params[:d] %>&kh=<%= params[:kh] %>&"+type+"=false";
}
$(function() {
        $('#map').gmap3({
            map: {
                options: {
                    center: {lat: <%= @d.center.split(",")[1] %>, lng: <%= @d.center.split(",")[0] %>},
                    zoom: 11
                }
            }
        });
        map = $("#map").gmap3("get");
        new google.maps.KmlLayer({url: "http://91.228.52.236/kml/<%= @d.filename %>"}).setMap(map);
        new google.maps.KmlLayer({url: "http://91.228.52.236/kml/<%= @d.filename %>"}).setMap(map);
        <% if params[:kh] and params[:kh]!="" %>
          new google.maps.KmlLayer({url: "http://91.228.52.236/kml/<%= @ckh.filename %>"}).setMap(map);
          new google.maps.InfoWindow({position: new google.maps.LatLng(<%= @ckh.center.split(",")[1] %>, <%= @ckh.center.split(",")[0] %>), content: '<%= @ckh.cname.strip %>'}).setMap(map);
        <%else%>
          <% @khoroo.each do |kh| %>
            new google.maps.KmlLayer({url: "http://91.228.52.236/kml/<%= kh.filename %>"}).setMap(map);
            new google.maps.InfoWindow({position: new google.maps.LatLng(<%= kh.center.split(",")[1] %>, <%= kh.center.split(",")[0] %>), content: '<%= kh.cname.strip %>'}).setMap(map);
          <% end %>
        <%end%>
          <% if @khoroolol %>
            <% @khoroolol.each do |k| %>
                  var coord = `<%=  k.coordinate %>`;
                  coords = [];
                  coord.split("\n").forEach(function(a,b){
                  c = a.split(",");
                  if(c.length > 1)
                     coords.push(new google.maps.LatLng(parseFloat(c[1]), parseFloat(c[0])));
                });
                var p = new google.maps.Polygon({
                paths: coords,
                strokeColor: '#FF0000',
                strokeOpacity:0.8,
                strokeWeight: 2,
                fillColor: '#FF0000',
                fillOpacity: 0.35,
                map: map
                });

              //p.setMap(map);
                  new google.maps.InfoWindow({position: new google.maps.LatLng(<%= k.center.split(",")[1] %>, <%= k.center.split(",")[0] %>), content: `<%= k.region_name.strip %>`}).setMap(map);
            <% end %>
          <% end %>
          
        
    });
</script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shuurkhai</title>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.3/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
	<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.3/js/materialize.min.js"></script>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <div class="nav-wrapper container">
      <a href="/" class="brand-logo">Шуурхай</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      	<li><a href="<%= region_path() %>">Нутаг дэвсгэр</a></li>
        <li><a href="<%= shop_path()%>">Шинэ дэлгүүр нэмэх</a></li>
        <li><a href="components.html">Шинэ байршил нэмэх</a></li>
      </ul>
    </div>
  </nav>
<div class="row">
<%= yield %>
</div>

</body>
</html>

app/views/shop/new.html.erb
<div class="container">
<div class="row">

<%= form_for(:shop, :url =>  shop_create_path(), :html=>{:class=>"col s4"} )do |f| %>
	<div class="row">
        <div class="input-field">
          	<%= f.text_field(:name) %>
  			<%= label_tag(:name, "Дэлгүүрийн нэр") %>
        </div>
  	</div>
  	<div class="row">
        <div class="input-field">
          <%= f.text_field(:latlng) %>
          <%= label_tag(:latlng, "latlng") %>
        </div>
  	</div>
  	<div class="row">
        <div class="input-field">
          <%= f.file_field(:logo) %>
        </div>
  	</div>
  	<div class="row">
        <div class="input-field">
          <%= f.text_field(:email) %>
          <%= label_tag(:email, "Майл хаяг") %>
        </div>
  	</div>
  <div class="row">
        <div class="input-field">
          <%= f.text_field(:phone) %>
          <%= label_tag(:phone, "Утасны дуугар") %>
        </div>
  	</div>
  	<div class="row">
        <div class="input-field">
          <%= f.text_area(:address,:class=>"materialize-textarea") %>
          <%= label_tag(:address, "Хаяг") %>
        </div>
  	</div>
  <%= f.submit("Хадгалах",:class=>"waves-light btn") %>
<% end %>
  <div class="col s8">
   	<div id="map" style="width:100%; min-height:450px;"></div>
  </div>
</div>
<div class="row">
	<hr>
  <table class="striped">
  <thead>
    <tr>
      <th>N</th>
      <th>Дэлгүүрийн нэр</th>
      <th>Утас</th>
      <th>Майл хаяг</th>
      <th>Байрлал</th>
      <th>Хаяг</th>
    </tr>
    <thead>
    <tbody>
    <% @shops.each do |shop, index| %>
      <tr>
        <td><%= shop.id %></td>
        <td><%= shop.name %></td>
        <td><%= shop.phone %></td>
        <td><%= shop.email %></td>
        <td><%= shop.latlng %></td>
        <td><%= shop.address %></td>
      </tr>  
    <% end %>
    </tbody>
  </table>
</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
    $("#map").gmap3({
    map:{
      options:{
        center:[47.9113293,106.9229857],
        zoom: 13
      }
    },
    marker:{
      values:[
        {latLng:[47.9113293,106.9229857], data:"Байрлал сонгох"}
      ],
      options:{
        draggable: true
      },
      events:{
        mouseover: function(marker, event, context){
          var map = $(this).gmap3("get"),
            infowindow = $(this).gmap3({get:{name:"infowindow"}});
          if (infowindow){
            infowindow.open(map, marker);
            infowindow.setContent(context.data);
          } else {
            $(this).gmap3({
              infowindow:{
                anchor:marker,
                options:{content: context.data}
              }
            });
          }
        },
        mouseout: function(){
          var infowindow = $(this).gmap3({get:{name:"infowindow"}});
          if (infowindow){
            infowindow.close();
          }
        },
        dragend: function(a){
          p = a.getPosition();
          $("#shop_latlng").val(p.k+", "+p.B);
        }
      }
    }
  });
});
</script>